default:
  image: ubuntu:22.04

stages:
  - build_development
  - build_production

build_development:
  stage: build_development
  tags:
    - dev
  script:
    - ssh gitlab-runner@172.16.4.70 "
      cd /var/www/Development_Gitlab/devitproject/ &&
      git reset --hard HEAD &&
      git clean -fd &&
      git pull https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.balitower.co.id/balitower/itproject.balitower.co.id.git development && 
      composer install &&
      npm install &&
      npm run build
      "

  only:
    - development
  when: on_success
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

build_production:
  stage: build_production
  tags:
    - prod
  script:
    - ssh gitlab-runner@172.16.2.70 "
      cd /var/www/Production_Gitlab/itproject/ &&
      git reset --hard HEAD &&
      git clean -fd &&
      git pull https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.balitower.co.id/balitower/itproject.balitower.co.id.git main && 
      composer install &&
      php artisan migrate &&
      npm install &&
      npm run build
      "

  only:
    - main
  when: on_success
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure