<?php

namespace Database\Factories;

use App\Models\MsProjectPriority;
use App\Models\MsProjectStatus;
use App\Models\Project;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Project>
 */
class ProjectFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * Master data (status/priority) and users are seeder-driven in this application,
     * so foreign keys default to existing rows and stay overridable. `project_no`
     * is generated by the model's `creating` hook, not set here.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $owner = User::query()->inRandomOrder()->value('id');
        $startDate = fake()->dateTimeBetween('-2 months', 'now');

        return [
            'status_id' => MsProjectStatus::query()->inRandomOrder()->value('id'),
            'priority_id' => MsProjectPriority::query()->inRandomOrder()->value('id'),
            'owner_id' => $owner,
            'owned_id' => $owner,
            'title' => fake()->catchPhrase(),
            'description' => fake()->paragraph(),
            'start_date' => $startDate->format('Y-m-d'),
            'due_date' => fake()->dateTimeBetween($startDate, '+3 months')->format('Y-m-d'),
            'progress' => 0,
            'sequence_number' => fake()->unique()->numberBetween(1, 100_000),
            'created_by' => $owner,
        ];
    }
}
